In [2]:
import pandas as pd

In [3]:
list = [1,2,3,4]

series = pd.Series(list)
series

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
scores = [75,82,38,49]
indexs = ["english","math","science","urdu"]

series = pd.Series(data=scores, index = indexs)
# series[["math","science"]]
series[["math","science"]]

math       82
science    38
dtype: int64

In [5]:
calories = {
    "day1":380,
    "day2": 420,
    "day3":220
}
sr = pd.Series(calories)
sr

day1    380
day2    420
day3    220
dtype: int64

In [6]:
data = {
    "calories":[380,420,390],
    "duration":[40,50,45],
    "name":["ali","abid","ghalib"]
}


df = pd.DataFrame(data)
print(df)
df.loc[[0,2]]

   calories  duration    name
0       380        40     ali
1       420        50    abid
2       390        45  ghalib

   calories  duration    name
0       380        40     ali
2       390        45  ghalib

In [7]:
df

   calories  duration    name
0       380        40     ali
1       420        50    abid
2       390        45  ghalib